### PR TITLE
feat(signal-handling): Backports handling of SIGTERM to 1.2.0

### PR DESCRIPTION
**Pull request by purew**
SIGTERM is used in ECS to signal to tasks that they should exit
before being killed. Newer versions of `logbt` does this and more.

It is however not trivial to migrate ECS tasks
on a shared cluster to a newer `logbt` due to
https://github.com/mapbox/logbt/issues/37.

This code thus adds SIGTERM handling to the 1.2.0 version
for the situations where upgrading `logbt` is not feasible.

### CODE REVIEW

**Comment by springmeyer** [comment]
Thanks @PureW - I've created `v1.2.x-release-series` to base this against. I'll review and push a release shortly.

**Comment by purew** [comment]
> Thanks @PureW - I've created `v1.2.x-release-series` to base this against. I'll review and push a release shortly.

Any updates on this?

I'm not sure what the error in CI is about, I'm guessing the build-environment isn't locked down to a specific version of _something_?

**Comment by springmeyer** [comment]
Thanks for the ping. Yeah, I've not dug into the error yet - but hopefully will be a quick fix once I do. What is the level of urgency you need for this?

**Comment by purew** [comment]
> Thanks for the ping. Yeah, I've not dug into the error yet - but hopefully will be a quick fix once I do. What is the level of urgency you need for this?

No real urgency, but I'd like to either merge the PR in https://github.com/mapbox/valhalla-live-traffic/pull/103 with the current vendored and patched `logbt` or a point-release from upstream.

**Comment by springmeyer** [comment]
Okay, https://github.com/mapbox/logbt/releases/tag/v1.2.1 is available now. This is passing on travis, so I'll merge shortly.

**Pull request merged**
