### PR TITLE
attemp to fix #28

### LINKED ISSUE #28: Quoting problems in args passed to logbt
I noticed that if the arg passed to `logbt` for [run commands](https://github.com/mapbox/logbt#run-logbt) have spaces they may no longer be quoted correctly once sent as a subcommand:

```
./logbt -- node -e "require('./test/lib/start').before(function() { console.log('* dev server ready'); });"
```

Will error with a JS parse error because the syntax is no longer valid. I think the quotes drop out. This may be unavoidable, but ticketing in case this is fixable. It may be fixable by quoting the `@*` passed to `logbt`.

### PR DESCRIPTION
**Pull request by springmeyer**
Fixes longstanding quoting problem. For some reason failing one test (don't have time right now to debug)

### CODE REVIEW

**Comment by Komzpa** [comment]
Hi, we're using this as a quirk in PostGIS builds - is there a chance this gets merged? :)

**Comment by springmeyer** [comment]
> is there a chance this gets merged?

Thanks for asking. But unfortunately not soon. It breaks tests on travis and I don't have time to debug why currently.

**Comment by Komzpa** [comment]
@springmeyer master branch is now also broken - may it be the same breakage? :)

**Comment by springmeyer** [comment]
@Komzpa this is now fixed and in master.

**Comment by Komzpa** [comment]
thanks! created https://trac.osgeo.org/postgis/ticket/4373

**Pull request merged**
